### ISSUE TITLE
AttributeError: 'float' object has no attribute 'split'

### ISSUE THREAD

**Issue by jforero2020** [yfukasawa/LongQC#14]
Hello....

When I run the below code, 

`python longQC.py sampleqc -x pb-rs2 -o prueba14 /home/jforero/mis_datos/tutoriales/anaconda3/prueba10.fasta -p 72 -d --fast -m 2 -i 10 --trim_output trimmedsequences`

It gives me an error saying that there is attribute error: 'float' object has no attribute 'split' .

I would like to know why this error comes about.

```
lq_coverage:2020-08-03 10:38:59,423:122:INFO:Estimation of coverage distribution finished.
Traceback (most recent call last):
  File "longQC.py", line 932, in <module>
    main(args)
  File "longQC.py", line 62, in main
    args.handler(args)
  File "longQC.py", line 592, in command_sample
    adp3_pos=np.mean(adp_pos3) if args.adp3 and adp_pos3 and np.mean(adp_pos3) > 0 else None)
  File "/datos/datosjforero/tutoriales/anaconda3/LongQC/lq_coverage.py", line 373, in plot_unmapped_frac_terminal
    t5l, t3l, il = self.__region_analysis(3, 1)
  File "/datos/datosjforero/tutoriales/anaconda3/LongQC/lq_coverage.py", line 596, in __region_analysis
    regs = [(int(reg.split('-')[0]), int(reg.split('-')[1])) for reg in str.split(',')]
AttributeError: 'float' object has no attribute 'split'
```

**Comment by jforero2020** [comment]
I was misplacing the input file

**Comment by ThDef** [comment]
Hi,
I got the same problem as you but I don't understand what you meant by "putting the input file wrong" ?
