### ISSUE TITLE
AttributeError: module 'pysam' has no attribute 'FastxFile'

### ISSUE THREAD

**Issue by jaquol** [yfukasawa/LongQC#15]
Hello,

I tried to execute LongQC with the following command:

```
python LongQC/longQC.py sampleqc -o longqc -x ont-rapid -p 4 test/test.fasta
```
However, I got the following error:
```
longQC:2020-08-04 11:17:56,650:165:INFO:Cmd: LongQC/longQC.py sampleqc -o longqc -x ont-rapid -p 4 test/test.fasta
longQC:2020-08-04 11:17:56,650:215:INFO:Preset "ont-rapid" was applied. Options --pb(--ont) is overwritten.
Traceback (most recent call last):
  File "LongQC/longQC.py", line 932, in <module>
    main(args)
  File "LongQC/longQC.py", line 62, in main
    args.handler(args)
  File "LongQC/longQC.py", line 281, in command_sample
    for (reads, n_seqs, n_bases) in open_seq_chunk(args.input, file_format_code, chunk_size=args.mem*1024**3, is_upper=True):
  File "/home/jovyan/LongQC/lq_utils.py", line 65, in open_seq_chunk
    yield from parse_fastx_chunk(fn, chunk_size, is_upper=is_upper)
  File "/home/jovyan/LongQC/lq_utils.py", line 268, in parse_fastx_chunk
    with pysam.FastxFile(fn) as f:
AttributeError: module 'pysam' has no attribute 'FastxFile'
```

Can you please help with that?

Thank you in advance!

**Comment by jaquol** [comment]
Updating pysam fixed the issue reported above.
