### ISSUE TITLE
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported

### ISSUE THREAD

**Issue by CptChiler** [yfukasawa/LongQC#24]
Im Running LongQC in my snakemake Nanopore genome pipe as on a cluster with no admin rights.

```
rule LongQC:
    input:
        'filtered_reads/{sample}.fastq.gz',
    output:
        'QC_results/{sample}',
    threads: t
    shell:
        '''
        python ~/SCRATCH_NOBAK/workplace_5z/LongQC/longQC.py sampleqc -x ont-ligation --ncpu {threads} -o {output} {input}
        '''
```
It runs fine with no error from minimap until the end.
I attached the output (without subsample.fastq[to big]) i think only the .html report is missing

[A22.zip](https://github.com/yfukasawa/LongQC/files/6271076/A22.zip)

Strange is it worked twice when testing after make:
```
python ~/SCRATCH_NOBAK/workplace_5z/LongQC/longQC.py sampleqc -x ont-ligation --ncpu 100 -o ~/SCRATCH_NOBAK/workplace_5z/LongQC/hybrid/A22 ~/SCRATCH_NOBAK/workplace_5z/hybrid/reads/long/A22.fastq.gz
```

**Error**
```
longQC:2021-04-07 12:55:48,036:489:INFO:Genarated the sample read length plot.
longQC:2021-04-07 12:55:48,037:491:INFO:Throughput: 500003168
longQC:2021-04-07 12:55:48,037:492:INFO:Length of longest read: 69248
longQC:2021-04-07 12:55:48,037:493:INFO:The number of reads: 57175
longQC:2021-04-07 12:55:48,038:524:INFO:Calculating overlaps of sampled reads...
longQC:2021-04-07 12:55:58,047:524:INFO:Calculating overlaps of sampled reads...
longQC:2021-04-07 12:56:08,055:524:INFO:Calculating overlaps of sampled reads...
longQC:2021-04-07 12:56:18,063:524:INFO:Calculating overlaps of sampled reads...
longQC:2021-04-07 12:56:28,071:524:INFO:Calculating overlaps of sampled reads...
longQC:2021-04-07 12:56:38,079:524:INFO:Calculating overlaps of sampled reads...
longQC:2021-04-07 12:56:48,087:524:INFO:Calculating overlaps of sampled reads...
longQC:2021-04-07 12:56:58,095:522:INFO:Process 66315 for ~/SCRATCH_NOBAK/workplace_5z/LongQC/minimap2-coverage/minimap2-coverage terminated.
longQC:2021-04-07 12:56:58,096:526:INFO:Overlap computation finished.
longQC:2021-04-07 12:57:08,103:598:INFO:Generating coverage related plots...
lq_coverage:2021-04-07 12:57:08,118:121:INFO:Estimating coverage distribution..
lq_coverage:2021-04-07 12:57:08,186:571:DEBUG:GaussianMixture(n_components=2)
lq_coverage:2021-04-07 12:57:08,192:576:INFO:The order of componens 0.009008786180148729 0.001502131247968907 
lq_coverage:2021-04-07 12:57:08,192:577:INFO:Means of components: 77.92692972768067 52.171159446345385 k=2
lq_coverage:2021-04-07 12:57:08,192:578:INFO:Covariances of components: 76.03986535434747 209.68414862634 k=2
lq_coverage:2021-04-07 12:57:08,229:123:INFO:Estimation of coverage distribution finished.
lq_coverage:2021-04-07 12:57:08,795:392:INFO:Coordinates of coverage analysis were parsed.
Traceback (most recent call last):
  File "~/SCRATCH_NOBAK/workplace_5z/LongQC/longQC.py", line 956, in <module>
    main(args)
  File "~/SCRATCH_NOBAK/workplace_5z/LongQC/longQC.py", line 62, in main
    args.handler(args)
  File "~/SCRATCH_NOBAK/workplace_5z/LongQC/longQC.py", line 611, in command_sample
    lc.plot_length_vs_coverage(fig_path_cl)
  File "/scratch/blumenscheitc/workplace_5z/LongQC/lq_coverage.py", line 479, in plot_length_vs_coverage
    self.__check_outlier_coverage(interval)
  File "/scratch/blumenscheitc/workplace_5z/LongQC/lq_coverage.py", line 500, in __check_outlier_coverage
    meds = stats['median'][np.where(stats['size']>=LqCoverage.LENGTH_BIN_THRESHOLD)[0]]
  File "~/.conda/envs/bio39/lib/python3.8/site-packages/pandas/core/series.py", line 877, in __getitem__
    return self._get_with(key)
  File "~/.conda/envs/bio39/lib/python3.8/site-packages/pandas/core/series.py", line 912, in _get_with
    return self.loc[key]
  File "~/.conda/envs/bio39/lib/python3.8/site-packages/pandas/core/indexing.py", line 895, in __getitem__
    return self._getitem_axis(maybe_callable, axis=axis)
  File "~/.conda/envs/bio39/lib/python3.8/site-packages/pandas/core/indexing.py", line 1113, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "~/.conda/envs/bio39/lib/python3.8/site-packages/pandas/core/indexing.py", line 1053, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis, raise_missing=False)
  File "~/.conda/envs/bio39/lib/python3.8/site-packages/pandas/core/indexing.py", line 1266, in _get_listlike_indexer
    self._validate_read_indexer(keyarr, indexer, axis, raise_missing=raise_missing)
  File "~/.conda/envs/bio39/lib/python3.8/site-packages/pandas/core/indexing.py", line 1321, in _validate_read_indexer
    raise KeyError(
KeyError: "Passing list-likes to .loc or [] with any missing labels is no longer supported. The following labels were missing: Int64Index([0], dtype='int64', name='Binned read length'). See https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike"
Error in job LongQC while creating output file QC_results/A22.
RuleException:
CalledProcessError in line 33 of /scratch/blumenscheitc/workplace_5z/long_reads_preprocess/Snakefile:
Command '
        python ~/SCRATCH_NOBAK/workplace_5z/LongQC/longQC.py sampleqc -x ont-ligation --ncpu 100 -o QC_results/A22 filtered_reads/A22.fastq.gz
        ' returned non-zero exit status 1
  File "/scratch/blumenscheitc/workplace_5z/long_reads_preprocess/Snakefile", line 33, in __rule_LongQC
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
Removing output files of failed job LongQC since they might be corrupted:
QC_results/A22
Skipped removing non-empty directory QC_results/A22
Will exit after finishing currently running jobs.
Exiting because a job execution failed. Look above for error message
```

**Comment by yfukasawa** [comment]
Hello @CptChiler,

Thank you for your interest in LongQC! This is maybe the same issue with #23. 
I pushed revised codes just before, and could you clone the latest repo of LongQC?
As you mentioned, steps until minimap2 finished without error. Table parsing step had some issues.

Version 1.2.0b should be able to handle your datasets faced some issues.
$python longQC.py --version
The command should return "LongQC 1.2.0b".

Yoshinori

**Comment by CptChiler** [comment]
Thanks for the fast answer @yfukasawa,
 
after new cloning its calling -> LongQC 1.2.0b and now its works perfectly.

Heads up for this amazing QC tool, good job mate.
