### ISSUE TITLE
Unable to open object (object 'UniqueGlobalKey' doesn't exist)

### ISSUE THREAD

**Issue by felipelira** [yfukasawa/LongQC#26]
Dear All,

I got an error that I can't find a solution. I paste here the output after the process breaks just at the beginning.

Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/disk2/Users/FLIR/Software/LongQC/lq_nanopore.py", line 155, in wrapper
    c_id  = get_channel_id(fast5) -1
  File "/disk2/Users/FLIR/Software/LongQC/lq_nanopore.py", line 120, in get_channel_id
    return int(f['/UniqueGlobalKey']['channel_id'].attrs['channel_number'])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/disk2/Software/Venv/venv36/lib/python3.6/site-packages/h5py/_hl/group.py", line 288, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'UniqueGlobalKey' doesn't exist)"

Do you have any clue about how to fix this and make the script runs normally?

Thank you in advance.

**Comment by yfukasawa** [comment]
Hello @felipelira,

Thank you for your interest in LongQC.

Can I ask the exact command you use?
From the error message, I think you would have tried `longQC.py runqc` for ONT data.
If this is the case, the format of Fast5 might have changed since the function was coded.
UniqueGlobalKey is the keyword previously existed in Fast5, but it may not exist anymore. I plan to deprecate runqc.
Having said, `longQC.py sampleqc` would run with ONT fastq file.

Hope this helps.

Yoshinori

**Comment by yfukasawa** [comment]
let me close this thread, and feel free to reopen when needed.
Y.

**Comment by fa2k** [comment]
I also have this problem when trying to QC a MinION run. I've used the Dockerfile to create a Docker image, but then had to convert to Singularity image.

As a background information, which is probably not relevant, I had to add two commands to the Docker image:
1. `RUN chmod -R a+rX /root` -- to run as a non-root user
2. `RUN pip install --upgrade h5py` -- Work around "undefined symbol: H5Pset_falp_ros3" error. Seems related to conda. https://github.com/h5py/h5py/issues/1880

After this, the singularity image produces the error in this issue. I'm using the `runqc` command on a MinION raw data output (also includes basecalled data). Here's the command and output:
``` 
$ singularity run -B $PWD:$PWD -W $PWD /boston/common/tools/longqc/20220131/longqc-20220131.sif runqc minion -o output_longqc no_sample/20220125_1444_MC-112514_FAR37726_776d5599/
lq_nanopore:2022-01-31 16:21:50,274:251:INFO:Started minion platform QC for no_sample/20220125_1444_MC-112514_FAR37726_776d5599/
lq_nanopore:2022-01-31 16:21:50,274:252:INFO:The num of channel:512, the num of process:15
lq_nanopore:2022-01-31 16:21:50,276:89:INFO:Go into subdir for listing fast5: no_sample/20220125_1444_MC-112514_FAR37726_776d5599/fast5_fail
lq_nanopore:2022-01-31 16:21:50,277:89:INFO:Go into subdir for listing fast5: no_sample/20220125_1444_MC-112514_FAR37726_776d5599/fastq_fail
lq_nanopore:2022-01-31 16:21:50,279:89:INFO:Go into subdir for listing fast5: no_sample/20220125_1444_MC-112514_FAR37726_776d5599/fast5_pass
lq_nanopore:2022-01-31 16:21:50,280:89:INFO:Go into subdir for listing fast5: no_sample/20220125_1444_MC-112514_FAR37726_776d5599/other_reports
lq_nanopore:2022-01-31 16:21:50,282:89:INFO:Go into subdir for listing fast5: no_sample/20220125_1444_MC-112514_FAR37726_776d5599/fastq_pass
lq_nanopore:2022-01-31 16:21:50,323:186:INFO:File list loaded. Size = 114
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/opt/conda/lib/python3.9/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/root/LongQC/lq_nanopore.py", line 155, in wrapper
    c_id  = get_channel_id(fast5) -1
  File "/root/LongQC/lq_nanopore.py", line 120, in get_channel_id
    return int(f['/UniqueGlobalKey']['channel_id'].attrs['channel_number'])
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/opt/conda/lib/python3.9/site-packages/h5py/_hl/group.py", line 305, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
KeyError: "Unable to open object (object 'UniqueGlobalKey' doesn't exist)"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/LongQC/longQC.py", line 957, in <module>
    main(args)
  File "/root/LongQC/longQC.py", line 63, in main
    args.handler(args)
  File "/root/LongQC/longQC.py", line 52, in command_run
    lq_nanopore.run_platformqc(args.platform, args.raw_data_dir, args.out, suffix=suf, n_channel=512)
  File "/root/LongQC/lq_nanopore.py", line 284, in run_platformqc
    process_uncompressed_multi(p, l, bag, fcs, kits, logger)
  File "/root/LongQC/lq_nanopore.py", line 190, in process_uncompressed_multi
    rtn_state = p.map(wrapper, l)
  File "/opt/conda/lib/python3.9/multiprocessing/pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/opt/conda/lib/python3.9/multiprocessing/pool.py", line 771, in get
    raise self._value
KeyError: "Unable to open object (object 'UniqueGlobalKey' doesn't exist)"
```

**Comment by fa2k** [comment]
I posted a comment, but I had missed the fact that you plan to deprecate runqc. I've deleted my comment, and will use sampleqc.
