### ISSUE TITLE
pandas.errors.EmptyDataError: No columns to parse from file - no Html file is generated

### ISSUE THREAD

**Issue by KristinaGagalova** [yfukasawa/LongQC#34]
Hi, 
I am having the following issue for few samples, two other samples were completed successfully and generated the Html file
Could you please take a look?
Thank you in advance 

```
longQC:2021-09-10 13:56:57,131:598:INFO:Generating coverage related plots...
Traceback (most recent call last):
  File "/home/kgagalova/src/LongQC/longQC.py", line 956, in <module>
    main(args)
  File "/home/kgagalova/src/LongQC/longQC.py", line 62, in main
    args.handler(args)
  File "/home/kgagalova/src/LongQC/longQC.py", line 602, in command_sample
    lc = LqCoverage(cov_path, isTranscript=args.transcript, control_filtering=pb_control)
  File "/home/kgagalova/src/LongQC/lq_coverage.py", line 88, in __init__
    self.df = pd.read_table(table_path, sep='\t', header=None, dtype={3: str, 4: str})
  File "/home/kgagalova/miniconda3/envs/py3.6bis/lib/python3.6/site-packages/pandas/io/parsers.py", line 767, in read_table
    return read_csv(**locals())
  File "/home/kgagalova/miniconda3/envs/py3.6bis/lib/python3.6/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/kgagalova/miniconda3/envs/py3.6bis/lib/python3.6/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/kgagalova/miniconda3/envs/py3.6bis/lib/python3.6/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/home/kgagalova/miniconda3/envs/py3.6bis/lib/python3.6/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/kgagalova/miniconda3/envs/py3.6bis/lib/python3.6/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 540, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by KristinaGagalova** [comment]
Looks related to #28
I will try to follow the suggestions you gave there

**Comment by yfukasawa** [comment]
Hello @KristinaGagalova,

Thank you for your interest in our tool. As you already noticed, `coverage_out.txt` may be an empty file for your case as mentioned in that thread.
Increasing RAM or reducing index size by `--index` could help. Default is 4G basepairs for index option (default of minimap2), and this usually uses 40-80 Gbytes RAM temporarily. `coverage_err.txt` would tell you how much memory was requested like below (the below example uses 67 Gbytes).

>[M::worker_pipeline::4336.261*10.99] mapped 5000 sequences. (Peak RSS: 67.012 GB)

feel free to post your questions.

**Comment by KristinaGagalova** [comment]
Thank you for the suggestion, decreasing the index size worked well.

**Comment by yfukasawa** [comment]
Thank you for letting know the outcome. I'm glad to know that. Let me close the ticket, and reopen if needed.
Y.
