### ISSUE TITLE
docker error: ImportError: /opt/conda/lib/python3.9/site-packages/h5py/defs.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3

### ISSUE THREAD

**Issue by JWDebler** [yfukasawa/LongQC#41]
Hi,
I just built the docker image (version 1.2) , but when I try to run it I get this error:

```
Traceback (most recent call last):
  File "/root/LongQC/longQC.py", line 29, in <module>
      import lq_nanopore             
  File "/root/LongQC/lq_nanopore.py", line 1, in <module>
    import os, sys, time, h5py, json  
  File "/opt/conda/lib/python3.9/site-packages/h5py/__init__.py", line 33, in <module>        
    from . import version       
  File "/opt/conda/lib/python3.9/site-packages/h5py/version.py", line 15, in <module> 
    from . import h5 as _h5     
  File "h5py/h5.pyx", line 1, in init h5py.h5    
ImportError: /opt/conda/lib/python3.9/site-packages/h5py/defs.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3
```
Any idea what the problem might be?
Cheers

**Comment by Sanrrone** [comment]
Dear @JWDebler , I was fighthing with the same error and I found you have to downgrade the `h5py` version and set it to `h5py'==3.1'`, after that the docker image works like a charm.

cheers

**Comment by yfukasawa** [comment]
thank you for sharing. will update some files.

Y.

**Comment by Robvh-git** [comment]
dear @yfukasawa, @Sanrrone ,

I built the docker environment today but I still receive this error. I run following command int he terminal:
```
sudo docker run -it \
-v PATH/WHERE/DATA/IS \
-v PATH/WHERE/DATA/IS \
longqc sampleqc \
-x ont-ligation \ 
-p 4 \
-o /output/out_dir \
input/sub_sample_10K.fastq
```
Which results in following error (same as above):
```

Traceback (most recent call last):
  File "/root/LongQC/longQC.py", line 29, in <module>
    import lq_nanopore
  File "/root/LongQC/lq_nanopore.py", line 1, in <module>
    import os, sys, time, h5py, json
  File "/opt/conda/lib/python3.9/site-packages/h5py/__init__.py", line 33, in <module>
    from . import version
  File "/opt/conda/lib/python3.9/site-packages/h5py/version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py/h5.pyx", line 1, in init h5py.h5
ImportError: /opt/conda/lib/python3.9/site-packages/h5py/defs.cpython-39-x86_64-linux-gnu.so: undefined symbol: H5Pset_fapl_ros3
```

I'm not familiar with docker, could you please specify the exact commands to downgrade the `h5py` version?
