### ISSUE TITLE
empty longqc_sdust.txt

### ISSUE THREAD

**Issue by lyj95618** [yfukasawa/LongQC#69]
Hi,

I want to try this tool on my pacbio long-read samples. Here is the command I used `python longQC.py sampleqc -x pb-hifi -o /hpf/largeprojects/TG/test_qc /hpf/largeprojects/long_read_RNA/pacbio/NUT22988_Isoseq-WT-10_CELL1/flnc.bam -p 8 --index 50M`

I got this error after the longqc_sdust.txt was created (**the file is empty**)
```
longQC:2024-03-26 14:11:50,629:367:INFO:Summary table /hpf/largeprojects/TG/test_qc/longqc_sdust.txt was made.
Traceback (most recent call last):
  File "/hpf/largeprojects/TG/miniforge3/envs/long_read_qc/bin/longQC.py", line 957, in <module>
    main(args)
  File "/hpf/largeprojects/TG/miniforge3/envs/long_read_qc/bin/longQC.py", line 62, in main
    args.handler(args)
  File "/hpf/largeprojects/TG/miniforge3/envs/long_read_qc/bin/longQC.py", line 370, in command_sample
    df_mask      = pd.read_table(lm.get_outfile_path(), sep='\t', header=None)
  File "/hpf/largeprojects/TG/miniforge3/envs/long_read_qc/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1405, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/hpf/largeprojects/TG/miniforge3/envs/long_read_qc/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/hpf/largeprojects/TG/miniforge3/envs/long_read_qc/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/hpf/largeprojects/TG/miniforge3/envs/long_read_qc/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
  File "/hpf/largeprojects/TG/miniforge3/envs/long_read_qc/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```
I guess pandas is complaining because my longqc_sdust.txt is empty?  

I checked some issues from other people and it seems like a memory issue? I have already requested 100G memory and lower the index to 50M. Is it still not enough? The size of my flnc bam is 35G

Thanks!
Laur

**Comment by KristinaGagalova** [comment]
I have the same error, and my `longqc_sdust.txt` file is populated. Any help on that?
I am running with docker

**Comment by lyj95618** [comment]
> I have the same error, and my `longqc_sdust.txt` file is populated. Any help on that? I am running with docker

So you also have this error even if your longqc_sdust.txt isn't empty? I can't get anything in my longqc_sdust.txt

Do you also use the flnc bam as the input?

Thanks,
Laur

**Comment by KristinaGagalova** [comment]
Hi, I am using a fastq.gz file as input. 
Have you tried different datasets/settings to see if you can get over the error?

**Comment by lyj95618** [comment]
I have tried a different input (mapped.bam) and a different dataset and it still doesn't work. 

Laur
