### ISSUE TITLE
Error pandas.errors.EmptyDataError: No columns to parse from file

### ISSUE THREAD

**Issue by husamia** [yfukasawa/LongQC#76]
I am running longQC using apptainer on am HPC

The command is the following 

`apptainer run docker://kchibs/longqc sampleqc -f -o /data/lgg_data/R_D/nanopore/progress/HMW12878_51kb/longqc -x ont-ligation /data/lgg_data/R_D/nanopore/progress/HMW12878_51kb/dorado_basecall_HMW12878_51kb_AS_sup.fastq`

this is the error I am getting

longQC:2024-09-13 09:57:03,055:525:INFO:Calculating overlaps of sampled reads...
longQC:2024-09-13 09:57:13,065:525:INFO:Calculating overlaps of sampled reads...
longQC:2024-09-13 09:57:23,153:523:INFO:Process 32982 for /root/LongQC/minimap2-coverage/minimap2-coverage terminated.
longQC:2024-09-13 09:57:23,167:527:INFO:Overlap computation finished.
longQC:2024-09-13 09:57:33,177:599:INFO:Generating coverage related plots...
Traceback (most recent call last):
  File "/root/LongQC/longQC.py", line 957, in <module>
    main(args)
  File "/root/LongQC/longQC.py", line 63, in main
    args.handler(args)
  File "/root/LongQC/longQC.py", line 603, in command_sample
    lc = LqCoverage(cov_path, isTranscript=args.transcript, control_filtering=pb_control)
  File "/root/LongQC/lq_coverage.py", line 88, in __init__
    self.df = pd.read_table(table_path, sep='\t', header=None, dtype={3: str, 4: str})
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1405, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

**Comment by geocarvalho** [comment]
Hi, same issue here running the docker on AWS EC2

```bash
$ run -v $PWD:$PWD quay.io/biocontainers/longqc:1.2.0c--hdfd78af_0 python /usr/local/bin/longQC.py sampleqc -x pb-hifi -p $(nproc) -o $PWD/sample_longqc $PWD/sample.bam
...
longQC:2025-01-02 20:05:49,218:366:INFO:Summary table /var/snap/amazon-ssm-agent/9881/download/sample_longqc/longqc_sdust.txt was made.
Traceback (most recent call last):
  File "/usr/local/bin/longQC.py", line 956, in <module>
    main(args)
  File "/usr/local/bin/longQC.py", line 62, in main
    args.handler(args)
  File "/usr/local/bin/longQC.py", line 369, in command_sample
    df_mask      = pd.read_table(lm.get_outfile_path(), sep='\t', header=None)
  File "/usr/local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 683, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/usr/local/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 69, in __init__
    self._reader = parsers.TextReader(self.handles.handle, **kwds)
  File "pandas/_libs/parsers.pyx", line 549, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```

**Comment by zhxiaokang** [comment]
Same problem here.

Installed longQC from Conda. Running command:
`python /home/.conda/envs/AAV/bin/longQC.py sampleqc -x ont-ligation -o aav/output/test FBA43310_pass_barcode01_0.fastq`
Getting the following error:
```
longQC:2025-01-17 07:37:04,695:169:INFO:Cmd: /home/.conda/envs/AAV/bin/longQC.py sampleqc -x ont-ligation -o aav/output/test FBA43310_pass_barcode01_0.fastq
longQC:2025-01-17 07:37:04,695:233:INFO:Preset "ont-ligation" was applied. Options --pb(--ont) is overwritten.
longQC:2025-01-17 07:37:05,146:306:INFO:Computation of the low complexity region started for a chunk 0
lq_mask:2025-01-17 07:37:05,245:111:INFO:New job was submitted: in->aav/output/test/analysis/tmp_0.fastq, out->aav/output/test/analysis/tmp_0.txt
longQC:2025-01-17 07:37:05,246:311:INFO:Adapter search is starting for a chunk 0.
longQC:2025-01-17 07:37:05,246:327:INFO:Computation of the GC fraction started for a chunk 0
lq_utils:2025-01-17 07:37:05,863:380:INFO:list for subsample is not initialized. Initializing now.
lq_adapt:2025-01-17 07:37:05,956:77:INFO:808 reads were skipped due to their short lengths.
lq_adapt:2025-01-17 07:37:05,957:90:INFO:Adapter Sequence: AATGTACTTCGTTCAGTTACGTATTGCT, max identity:0.965517 and the number of trimmed reads: 7783
lq_adapt:2025-01-17 07:37:06,234:42:INFO:1229 reads were skipped due to their short lengths.
lq_adapt:2025-01-17 07:37:06,234:92:INFO:Adapter Sequence: GCAATACGTAACTGAACG, max identity:0.833333 and the number of trimmed reads: 8
longQC:2025-01-17 07:37:06,239:332:INFO:Adapter search has done for a chunk 0.
longQC:2025-01-17 07:37:06,239:342:INFO:subsample finished for chunk 0.
longQC:2025-01-17 07:37:06,239:362:INFO:Input file parsing was finished. #seqs:9693, #bases: 14397782
lq_mask:2025-01-17 07:37:06,240:114:INFO:Waiting completion of all of jobs...
lq_mask:2025-01-17 07:37:06,249:117:INFO:sdust jobs finished.
lq_mask:2025-01-17 07:37:06,249:87:INFO:sdust output file aav/output/test/longqc_sdust.txt was made.
lq_mask:2025-01-17 07:37:06,256:93:INFO:tmp file aav/output/test/analysis/tmp_0.fastq was removed.
lq_mask:2025-01-17 07:37:06,256:93:INFO:tmp file aav/output/test/analysis/tmp_0.txt was removed.
longQC:2025-01-17 07:37:06,256:366:INFO:Summary table aav/output/test/longqc_sdust.txt was made.
Traceback (most recent call last):
  File "/home/.conda/envs/AAV/bin/longQC.py", line 956, in <module>
    main(args)
  File "/home/.conda/envs/AAV/bin/longQC.py", line 62, in main
    args.handler(args)
  File "/home/.conda/envs/AAV/bin/longQC.py", line 369, in command_sample
    df_mask      = pd.read_table(lm.get_outfile_path(), sep='\t', header=None)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/AAV/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1405, in read_table
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/AAV/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/AAV/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/AAV/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.conda/envs/AAV/lib/python3.12/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

```
The output folder was created, but all empty.

**Comment by GACGAMA** [comment]
I'm getting the same error with PacBio HiFi reads

`
lq_mask:2025-02-10 08:20:55,896:93:INFO:tmp file /scratch4/nsobrei2/ggama1/longread_cnv_sv/longqc/HCC1395BL_TUMOR_BREAST_CANCER_PACBIO_SUBSAMPLED_fastq/analysis/tmp_10.txt was removed.
longQC:2025-02-10 08:20:55,897:366:INFO:Summary table /scratch4/nsobrei2/ggama1/longread_cnv_sv/longqc/HCC1395BL_TUMOR_BREAST_CANCER_PACBIO_SUBSAMPLED_fastq/longqc_sdust.txt was made.
Traceback (most recent call last):
  File "/scratch4/nsobrei2/ggama1/conda/.conda/envs/longqc/bin/longQC.py", line 956, in <module>
    main(args)
  File "/scratch4/nsobrei2/ggama1/conda/.conda/envs/longqc/bin/longQC.py", line 62, in main
    args.handler(args)
  File "/scratch4/nsobrei2/ggama1/conda/.conda/envs/longqc/bin/longQC.py", line 369, in command_sample
    df_mask      = pd.read_table(lm.get_outfile_path(), sep='\t', header=None)
  File "/scratch4/nsobrei2/ggama1/conda/.conda/envs/longqc/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1405, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/scratch4/nsobrei2/ggama1/conda/.conda/envs/longqc/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/scratch4/nsobrei2/ggama1/conda/.conda/envs/longqc/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/scratch4/nsobrei2/ggama1/conda/.conda/envs/longqc/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
  File "/scratch4/nsobrei2/ggama1/conda/.conda/envs/longqc/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file`

**Comment by silviagenome** [comment]
Hi!

I am getting the same error and I used the Docker version so i think maybe there is a problem with the format of my data. My reads are PacBio Revio.

I attach the error I get:

longQC:2025-02-20 10:06:09,728:599:INFO:Generating coverage related plots...
Traceback (most recent call last):
  File "/root/LongQC/longQC.py", line 957, in <module>
    main(args)
  File "/root/LongQC/longQC.py", line 63, in main
    args.handler(args)
  File "/root/LongQC/longQC.py", line 603, in command_sample
    lc = LqCoverage(cov_path, isTranscript=args.transcript, control_filtering=pb_control)
  File "/root/LongQC/lq_coverage.py", line 88, in __init__
    self.df = pd.read_table(table_path, sep='\t', header=None, dtype={3: str, 4: str})
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1405, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
  File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file

**Comment by silviagenome** [comment]
Hi!

I am getting the same error and I used the Docker version so i think maybe there is a problem with the format of my data. My reads are PacBio Revio.

I attach the error I get:

`longQC:2025-02-20 10:06:09,728:599:INFO:Generating coverage related plots...
Traceback (most recent call last):
File "/root/LongQC/longQC.py", line 957, in
main(args)
File "/root/LongQC/longQC.py", line 63, in main
args.handler(args)
File "/root/LongQC/longQC.py", line 603, in command_sample
lc = LqCoverage(cov_path, isTranscript=args.transcript, control_filtering=pb_control)
File "/root/LongQC/lq_coverage.py", line 88, in init
self.df = pd.read_table(table_path, sep='\t', header=None, dtype={3: str, 4: str})
File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1405, in read_table
return _read(filepath_or_buffer, kwds)
File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
parser = TextFileReader(filepath_or_buffer, **kwds)
File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in init
self._engine = self._make_engine(f, self.engine)
File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
return mapping[engine](f, **self.options)
File "/opt/conda/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in init
self._reader = parsers.TextReader(src, **kwds)
File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.cinit
pandas.errors.EmptyDataError: No columns to parse from file`

**Comment by geocarvalho** [comment]
I just moved my QC to [cramino](https://github.com/wdecoster/cramino)

**Comment by Pyramtee** [comment]
Hi, I am getting the same error using conda env.
```shell
longQC:2025-04-02 05:34:35,949:598:INFO:Generating coverage related plots...
Traceback (most recent call last):
  File "/public/home/rongzz/tools/LongQC/longQC.py", line 956, in <module>
    main(args)
  File "/public/home/rongzz/tools/LongQC/longQC.py", line 62, in main
    args.handler(args)
  File "/public/home/rongzz/tools/LongQC/longQC.py", line 602, in command_sample
    lc = LqCoverage(cov_path, isTranscript=args.transcript, control_filtering=pb_control)
  File "/public/home/rongzz/tools/LongQC/lq_coverage.py", line 88, in __init__
    self.df = pd.read_table(table_path, sep='\t', header=None, dtype={3: str, 4: str})
  File "/home1/rongzz/miniconda3/envs/tool_longqc/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1405, in read_table
    return _read(filepath_or_buffer, kwds)
  File "/home1/rongzz/miniconda3/envs/tool_longqc/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home1/rongzz/miniconda3/envs/tool_longqc/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
  File "/home1/rongzz/miniconda3/envs/tool_longqc/lib/python3.9/site-packages/pandas/io/parsers/readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
  File "/home1/rongzz/miniconda3/envs/tool_longqc/lib/python3.9/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 93, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "parsers.pyx", line 581, in pandas._libs.parsers.TextReader.__cinit__
pandas.errors.EmptyDataError: No columns to parse from file
```
It also generates another err file, `analysis/minimap2/coverage_err.txt`:
```txt
Homopolymer compression is not applied.
Warning: Apply default c=3 instead.
Warning: -s shouldn't be zero. Apply default s=100000 instead.
Warning: Apply default g=10000 instead.
Warning: Apply default n=3 instead.
Warning: Apply default m=40 instead.
Warning: Apply default s=25 instead.
Warning: Apply default a=2000 instead.
Warning: Apply default r=0.4 instead.
=== Parameters are listed below ===
Inputs are target: /home1/rongzz/Projects/1-Pangenome/output/LBFC20250298-01/1.LongQC/25ZF03382/analysis/pbbam_converted_seq_file.fastq, query: /home1/rongzz/Projects/1-Pangenome/output/LBFC20250298-01/1.LongQC/25ZF03382/analysis/subsample.fastq
kmer 12, window 5, index loading size 4000000000
min-score 40, min-score-med 80, min-score-good 160, max-gap 10000, min-cnt 3
Homo-polymer compression: 0, Filtering: 0, minimizer-count: 0
max-overhang 2000, min-overlaplen 0, min-overapratio 0.40
num of threads 20, num of query seqs 100000
===
[M::main::2.385*1.05] loaded 5000 sequence(s). Total m_cnt: 31673380 (Peak RSS: 6.382 GB)
[M::mm_idx_gen::112.098*1.77] collected minimizers
[M::mm_idx_gen::168.361*2.18] sorted minimizers
[M::mm_mapopt_update::168.494*2.18] mid_occ = 22444
[M::main::168.494*2.18] loaded/built the index for 212159 target sequence(s)
```

**Comment by lschreib** [comment]
Hi everyone, I got the same error but discovered that this issue was already discussed and solved under #28.

Basically the error means that the process ran out of memory. This can be addressed by lowering the index parameter (-i/--index) for the minimap step. For my dataset lowering it from the default '4G' to '1G'  (_python3 longQC.py sampleqc -x pb-sequel -i 1G  ..._ ) solved the issue.
